In [1]:
import pandas as pd
data = pd.read_csv('cleaned_data.csv')
data = pd.DataFrame(data)  # Placeholder for the actual data cleaning process
data =data.drop(columns=['Gender', 'Segment', 'nps_category', 'last_interaction_date'])

In [2]:
data

,CustomerID,Age,NPS,account_age_days,age_group,total_purchase_value,total_frequency,product_diversity,Plan,subscription_duration_days,...,rfm_segment,Gender_Female,Gender_Male,Segment_Segment A,Segment_Segment B,Segment_Segment C,nps_category_Detractor,nps_category_Passive,nps_category_Promoter,days_since_last_interaction
0,1001,31,3,1069,0,3994.72,38,7,2689.622546,871,...,4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,523
1,1002,66,6,1455,2,2844.35,4,3,2828.649426,290,...,4,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,17
2,1003,36,3,1341,1,1866.52,14,3,2790.271692,319,...,3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,360
3,1004,62,1,1033,2,1378.64,28,5,2905.696003,803,...,4,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,50
4,1005,68,3,1366,2,2425.05,39,6,2714.759176,580,...,2,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12478,13479,55,8,338,2,1196.56,14,3,2790.271692,745,...,4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,82
12479,13480,29,7,930,0,710.57,1,1,2859.778143,18,...,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,55
12480,13481,38,1,809,1,5154.42,63,10,2723.138567,20,...,1,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,22
12481,13482,26,0,920,0,6055.16,58,9,2816.218537,484,...,2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,45


In [3]:
# Logistic Regression (Target Variable: ChurnLabel)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
X = data.drop(columns=['ChurnLabel', 'CustomerID'], axis=1)
y = data['ChurnLabel']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

# Initialize and train the Logistic Regression model
logreg = LogisticRegression(max_iter=2000, random_state=42)
logreg.fit(X_train, y_train)
# Make predictions on the test set
y_pred = logreg.predict(X_test)
# Evaluate the model
from sklearn.metrics import confusion_matrix, classification_report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")

Confusion Matrix:
[[1208   26]
 [  33 1230]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497

Accuracy: 97.64%


c:\Users\bubut\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
pd.set_option('display.max_columns', None)  # Show all columns when displaying DataFrame

# Feature Selection

### Mutual Information

In [5]:
# Feature Selection Using Mutual Information
from sklearn.feature_selection import mutual_info_classif

mutual_data = data.copy()

target = mutual_data['ChurnLabel'] 
features = mutual_data.drop(columns=['ChurnLabel', 'CustomerID'], axis = 1) #1 means y-axis or column and 0 means x-axis or row

mi_scores = mutual_info_classif(features, target)

In [6]:
mi_df = pd.DataFrame({
    'Feature': features.columns,
    'Score': mi_scores
})


# Select top features based on mutual information scores
top_features = mi_df[mi_df['Score'] > 0]['Feature'].tolist()

mutual_data = mutual_data[['CustomerID'] + top_features + ['ChurnLabel']]
mutual_data.head()

,CustomerID,Age,NPS,total_purchase_value,product_diversity,Plan,subscription_duration_days,total_interactions,total_late_payments,payment_count,late_payment_rate,payment_risk_score,TimeSpent(minutes),engagement_ratio,engagement_intensity,click_count,unique_pages,cart_conversion_rate,page_diversity,Logins,avg_rating,avg_comment_length,emails_opened,open_rate,click_rate,click_through_rate,Recency,Frequency,Monetary,r_score,rfm_score,rfm_segment,Segment_Segment B,Segment_Segment C,nps_category_Detractor,nps_category_Passive,nps_category_Promoter,days_since_last_interaction,ChurnLabel
0,1001,31,3,3994.72,7,2689.622546,871,4,40,3,10.00,400.00,15,0.300000,735,4,13,0.320000,0.520000,19,1.0,96.0,8,0.888889,0.888889,0.888889,523,722,3994.72,1,9,4,1.0,0.0,1.0,0.0,0.0,523,1
1,1002,66,6,2844.35,3,2828.649426,290,19,10,3,2.50,25.00,9,0.089109,900,9,13,0.320000,0.520000,9,2.0,108.0,9,0.900000,0.900000,0.900000,17,36,2844.35,5,9,4,0.0,1.0,1.0,0.0,0.0,17,0
2,1003,36,3,1866.52,3,2790.271692,319,3,8,3,2.00,16.00,97,48.500000,97,3,7,0.153846,0.538462,19,4.0,72.0,8,0.888889,0.888889,0.888889,360,266,1866.52,1,6,3,1.0,0.0,1.0,0.0,0.0,360,0
3,1004,62,1,1378.64,5,2905.696003,803,59,79,3,19.75,1560.25,31,1.192308,775,16,14,0.312500,0.291667,4,1.0,78.0,10,0.909091,0.909091,0.909091,50,112,1378.64,3,7,4,0.0,1.0,1.0,0.0,0.0,50,1
4,1005,68,3,2425.05,6,2714.759176,580,10,2,3,0.50,1.00,51,0.653846,3927,9,12,0.548387,0.387097,12,3.0,99.0,7,0.875000,0.875000,0.875000,11,468,2425.05,5,11,2,0.0,1.0,1.0,0.0,0.0,11,0


In [7]:
mi_df.sort_values(by='Score', ascending=False)


,Feature,Score
15,payment_risk_score,0.579460
12,total_late_payments,0.576226
14,late_payment_rate,0.575747
11,total_interactions,0.284312
17,TimeSpent(minutes),0.272715
1,NPS,0.235679
19,engagement_intensity,0.145999
18,engagement_ratio,0.137909
56,nps_category_Detractor,0.105455
43,Recency,0.065066


In [8]:
# Train a Logistic Regression model using only the selected features
X_mutual = mutual_data.drop(columns=['ChurnLabel', 'CustomerID'], axis=1)
y_mutual = mutual_data['ChurnLabel']

# Train-test split
X_train_mutual, X_test_mutual, y_train_mutual, y_test_mutual = train_test_split(X_mutual, y_mutual, test_size=0.2, random_state=42, stratify=y_mutual)
logreg_mutual = LogisticRegression(max_iter=2000, random_state=42)
logreg_mutual.fit(X_train_mutual, y_train_mutual)

# Predictions and evaluation
y_pred_mutual = logreg_mutual.predict(X_test_mutual)
print("Confusion Matrix (Mutual Information):")
print(confusion_matrix(y_test_mutual, y_pred_mutual))
print("\nClassification Report (Mutual Information):")
print(classification_report(y_test_mutual, y_pred_mutual))
print(f"Accuracy (Mutual Information): {accuracy_score(y_test_mutual, y_pred_mutual) * 100:.2f}%")

Confusion Matrix (Mutual Information):
[[1208   26]
 [  32 1231]]

Classification Report (Mutual Information):
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497

Accuracy (Mutual Information): 97.68%


c:\Users\bubut\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Intuition


In [ ]:
# Feature Selection Based on Intuition
# I will select them by removing features with an MI score of less than 0.01
intuitive_features = mi_df[mi_df['Score'] >= 0.01]['Feature'].tolist()
print(len(intuitive_features), "features selected based on intuition.")
intuitive_data = data[['CustomerID'] + intuitive_features + ['ChurnLabel']]
intuitive_data.head()

# Train a Logistic Regression model using only the intuitively selected features
X_intuitive = intuitive_data.drop(columns=['ChurnLabel', 'CustomerID'], axis=1)
y_intuitive = intuitive_data['ChurnLabel']

# Train-test split
X_train_intuitive, X_test_intuitive, y_train_intuitive, y_test_intuitive = train_test_split(X_intuitive, y_intuitive, test_size=0.2, random_state=42, stratify=y_intuitive)

# Initialize and train the Logistic Regression model
logreg_intuitive = LogisticRegression(max_iter=2000, random_state=42)
logreg_intuitive.fit(X_train_intuitive, y_train_intuitive)
# Predictions and evaluation
y_pred_intuitive = logreg_intuitive.predict(X_test_intuitive)
print("Confusion Matrix (Intuitive Selection):")
print(confusion_matrix(y_test_intuitive, y_pred_intuitive))
print("\nClassification Report (Intuitive Selection):")
print(classification_report(y_test_intuitive, y_pred_intuitive))
print(f"Accuracy (Intuitive Selection): {accuracy_score(y_test_intuitive, y_pred_intuitive) * 100:.2f}%")

18 features selected based on intuition.
Confusion Matrix (Intuitive Selection):
[[1208   26]
 [  33 1230]]

Classification Report (Intuitive Selection):
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497

Accuracy (Intuitive Selection): 97.64%


c:\Users\bubut\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
# Using Pickle to Save the Models
import pickle

# Save the original logistic regression model
with open('logreg_model.pkl', 'wb') as f:
    pickle.dump(logreg_mutual, f) 

# Load the model back
with open('logreg_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

# Test the loaded model
y_loaded_pred = loaded_model.predict(X_test_mutual)
print("Confusion Matrix (Loaded Model):")
print(confusion_matrix(y_test_mutual, y_loaded_pred))
print("\nClassification Report (Loaded Model):")
print(classification_report(y_test_mutual, y_loaded_pred))



# wb means write binary mode
# rb means read binary mode
# The pickle module is used for serializing and deserializing Python objects.

Confusion Matrix (Loaded Model):
[[1208   26]
 [  32 1231]]

Classification Report (Loaded Model):
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497



In [11]:
# Create 1 row of sample data for prediction
columns = ['CustomerID', 'Age', 'NPS', 'total_purchase_value', 'total_frequency',
       'product_diversity', 'Plan', 'subscription_duration_days',
       'total_interactions', 'total_late_payments', 'payment_count',
       'late_payment_rate', 'payment_risk_score', 'TimeSpent(minutes)',
       'engagement_ratio', 'engagement_intensity', 'add_to_cart_count',
       'search_count', 'cart_conversion_rate', 'page_diversity', 'Logins',
       'frequency_score', 'sentiment_score', 'is_negative', 'emails_sent',
       'open_rate', 'click_rate', 'click_through_rate', 'marketing_engagement',
       'Recency', 'Monetary', 'r_score', 'f_score', 'rfm_score', 'rfm_segment',
       'Segment_Segment B', 'nps_category_Detractor', 'nps_category_Passive',
       'nps_category_Promoter', 'days_since_last_interaction', 'ChurnLabel']


In [12]:
# Create a sample data using the first row of mutual_data, each column will randomly add or subtract 10% of its value
import numpy as np
sample_data = mutual_data.iloc[0].copy()
for col in mutual_data.columns:
    if col != 'CustomerID' and col != 'ChurnLabel':
        variation = sample_data[col] * 0.1
        sample_data[col] += np.random.uniform(-variation, variation)

sample_data = sample_data.drop(labels=['CustomerID', 'ChurnLabel'])
sample_data = sample_data.values

# Turn to dataframe
sample_df = pd.DataFrame([sample_data], columns=mutual_data.columns.drop(['CustomerID', 'ChurnLabel']))
sample_df.head()

,Age,NPS,total_purchase_value,product_diversity,Plan,subscription_duration_days,total_interactions,total_late_payments,payment_count,late_payment_rate,payment_risk_score,TimeSpent(minutes),engagement_ratio,engagement_intensity,click_count,unique_pages,cart_conversion_rate,page_diversity,Logins,avg_rating,avg_comment_length,emails_opened,open_rate,click_rate,click_through_rate,Recency,Frequency,Monetary,r_score,rfm_score,rfm_segment,Segment_Segment B,Segment_Segment C,nps_category_Detractor,nps_category_Passive,nps_category_Promoter,days_since_last_interaction
0,28.105176,3.24002,3781.446863,7.289907,2924.466125,852.543479,4.193176,42.80348,3.058895,9.851197,376.072902,14.229146,0.276167,728.285915,3.862232,12.828014,0.326519,0.549636,19.662553,0.905808,95.031503,7.231029,0.949653,0.819595,0.876464,520.299446,743.810282,4276.780425,0.931327,8.303435,4.337044,1.036738,0.0,1.081493,0.0,0.0,539.191903


In [15]:
def inference(sample):
    # Load the saved model
    with open('logreg_model.pkl', 'rb') as f:
        model = pickle.load(f)
    
    # Make prediction
    prediction = model.predict(sample)
    return (f"The churn prediction is: {prediction}")

inference(sample_df)

'The churn prediction is: [1]'

In [ ]:
# from sklearn.model_selection import RandomizedSearchCV
# from sklearn.tree import DecisionTreeClassifier

# def train_and_evaluate: